[project]
name = "minimal_codebase"
version = "0.1.0"
description = "PDFサムネイルマージャー等のツール群"
authors = ["Your Name <your.email@example.com>"]
requires-python = ">=3.10"
dependencies = [
    "PyQt6",
    "PyMuPDF"
]

[tool.uv] 

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
